services:
  - type: web
    name: paymaster
    env: docker
    plan: free
    healthCheckPath: /metrics
    envVars:
      - key: PORT
        value: "10000"
      - key: SOLANA_NETWORK
        value: devnet
      - key: TRUST_PROXY
        value: "1"
      - key: REDIS_URL
        fromService:
          type: redis
          name: paymaster-redis
          property: connectionString
      - key: SERVER_PRIVATE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: ALLOWED_PROGRAM_IDS
        sync: false
      - key: BLACKLIST_ADDRESSES
        sync: false
      - key: MAX_SPONSORED_TRANSACTIONS
        value: "5"
      - key: MAX_SPONSORED_AMOUNT_SOL
        value: "0.0001"

  - type: redis
    name: paymaster-redis
    plan: free
    ipAllowList: []